---
# https://github.com/codecov/example-perl/blob/master/github.yml
name: Code coverage - codecov.io

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: codecov
    timeout-minutes: 30
    container:
      image: perl:stable
    steps:
      - uses: actions/checkout@v7
      - name: Install Dependencies
        run: |
          cpanm --quiet --notest --installdeps .
          cpanm --quiet --notest Module::Build Devel::Cover Devel::Cover::Report::Codecov
      - name: Build module
        env:
          AUTHOR_TESTING: 1
          AUTOMATED_TESTING: 1
        run: |
          perl Makefile.PL
          make
      - name: Submit codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          AUTOMATED_TESTING: 1
        run: |
          CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }} cover -test
          CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }} cover -report codecov
